authors = ["4x8Matrix"]
description = "A penguin centric discord-bot"
entrypoint = "./Source/init.luau"
include = ["Source", "Source"]
licence = "None"
name = "pengu-discord-bot"
repository = "https://github.com/4x8Matrix/Pengu-Bot"
version = "0.1.0"

[dependencies]
"DiscordLuau/Discord-Luau" = "DiscordLuau/Discord-Luau"

[scripts]
